build: false
image:
  - Visual Studio 2019
  - Ubuntu
  - macOS

clone_depth: 3

branches:
  only:
    - master

test_script:
  - ps: .\paths.ps1
  - sh: pwsh -File paths.ps1

artifacts:
  - path: logs
